-- Generated by generate-modules.sh; fallback values used for plain cabal build
module RPKI.Meta.GitVersionInfo where

gitBranch :: String
gitBranch = "sqlite"

gitHash :: String
gitHash = "0b8e71e8b86431cdc2135e380c03f0a35b842d29"

gitCommitDate :: String
gitCommitDate = "2026-08-30 16:16:24 +0200"

gitCommitCount :: Int
gitCommitCount = 2749

gitDirty :: Bool
gitDirty = True
