-- Generated by generate-modules.sh; fallback values used for plain cabal build
module RPKI.Meta.GitVersionInfo where

gitBranch :: String
gitBranch = "fix-cache-poisoning"

gitHash :: String
gitHash = "2245b27aaa27be02a56450d772591d532042c6c8"

gitCommitDate :: String
gitCommitDate = "2026-08-26 19:12:19 +0200"

gitCommitCount :: Int
gitCommitCount = 2728

gitDirty :: Bool
gitDirty = True
