-- Generated by generate-modules.sh; fallback values used for plain cabal build
module RPKI.Meta.GitVersionInfo where

gitBranch :: String
gitBranch = "sqlite-mem-opt"

gitHash :: String
gitHash = "692ca619713e86759ac75753147d8098535d5ade"

gitCommitDate :: String
gitCommitDate = "2026-09-07 22:49:41 +0100"

gitCommitCount :: Int
gitCommitCount = 2795

gitDirty :: Bool
gitDirty = True
