# Look there https://gitlab.b-data.ch/ghc/ghc-musl/container_registry/381?after=NTA
FROM glcr.b-data.ch/ghc/ghc-musl:9.10.3-int-native-linux-amd64 as rpki-prover-builder

RUN apk add --update --no-cache xz-static

