#!/bin/sh
# POSIX sh: this is sourced from both bash build scripts and
# build-openbsd.sh (plain /bin/sh, no bash on OpenBSD base).

# Calculate hash of the sources and update it in the RPKI.Meta.Version module,
# it is used for determining upgrades at the runtime.

# Genrate git info module

GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
GIT_HASH=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
GIT_DATE=$(git log -1 --format='%ci' 2>/dev/null || echo "unknown")
GIT_COUNT=$(git rev-list --count HEAD 2>/dev/null || echo "0")
GIT_DIRTY=$([ -n "$(git status --porcelain 2>/dev/null)" ] && echo "True" || echo "False")

cat > src/RPKI/Meta/GitVersionInfo.hs << EOF
-- Generated by generate-modules.sh; fallback values used for plain cabal build
module RPKI.Meta.GitVersionInfo where

gitBranch :: String
gitBranch = "$GIT_BRANCH"

gitHash :: String
gitHash = "$GIT_HASH"

gitCommitDate :: String
gitCommitDate = "$GIT_DATE"

gitCommitCount :: Int
gitCommitCount = $GIT_COUNT

gitDirty :: Bool
gitDirty = $GIT_DIRTY
EOF

# Generate source hash module to keep track of the source tree changes
#
versionModule="src/RPKI/Meta/UniqueId.hs"

# sha256sum is GNU coreutils and isn't present on OpenBSD/macOS by default;
# fall back to shasum (macOS) or the BSD "sha256" tool (OpenBSD/FreeBSD/NetBSD).
sha256() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum | awk '{print $1;}'
    elif command -v shasum >/dev/null 2>&1; then
        shasum -a 256 | awk '{print $1;}'
    elif command -v sha256 >/dev/null 2>&1; then
        sha256 -q
    else
        echo "No sha256/sha256sum/shasum utility found in PATH" >&2
        exit 1
    fi
}

hash=$( (echo "rpki-prover.cabal";
        echo "cabal.project";
        echo "cabal.project.freeze";
        find src app  -type f -name \*.hs) | \
        grep -v "$versionModule" | \
        sort | \
        xargs cat | \
        grep -v -e '^[[:space:]]*$' | \
        grep -v '^[[:space:]]*--' | sha256)

tmpfile=`mktemp`
cat $versionModule | sed "s/srcHash#.*#srcHash/srcHash#$hash#srcHash/g" > "${tmpfile}"
mv "${tmpfile}" $versionModule
