#!/bin/bash 

# Calculate hash of the sources and update it in the RPKI.Meta.Version module,
# it is used for determining upgrades at the runtime.

# Genrate git info module

GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
GIT_HASH=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
GIT_DATE=$(git log -1 --format='%ci' 2>/dev/null || echo "unknown")
GIT_COUNT=$(git rev-list --count HEAD 2>/dev/null || echo "0")
GIT_DIRTY=$([ -n "$(git status --porcelain 2>/dev/null)" ] && echo "True" || echo "False")

cat > src/RPKI/Meta/GitVersionInfo.hs << EOF
-- Generated by generate-modules.sh; fallback values used for plain cabal build
module RPKI.Meta.GitVersionInfo where

gitBranch :: String
gitBranch = "$GIT_BRANCH"

gitHash :: String
gitHash = "$GIT_HASH"

gitCommitDate :: String
gitCommitDate = "$GIT_DATE"

gitCommitCount :: Int
gitCommitCount = $GIT_COUNT

gitDirty :: Bool
gitDirty = $GIT_DIRTY
EOF

# Generate source hash module to keep track of the source tree changes 
# 
versionModule="src/RPKI/Meta/UniqueId.hs"

hash=$((echo "rpki-prover.cabal"; 
        echo "cabal.project";
        find src app  -type f -name \*.hs) | \
        grep -v "$versionModule" | \
        sort | \
        xargs cat | \
        grep -v -e '^[[:space:]]*$' | \
        grep -v '^[[:space:]]*--' | sha256sum | awk '{print $1;}')

tmpfile=`mktemp`
cat $versionModule | sed "s/srcHash#.*#srcHash/srcHash#$hash#srcHash/g" > "${tmpfile}"
mv "${tmpfile}" $versionModule