#!/usr/bin/env bash
#
# Turns pkg/packages/<codename>/*.deb into a signed APT repository that can be
# served by any plain static web server -- GitHub Pages in particular.
#
#   ./pkg/apt-repo/build-apt-repo.sh --key 0xDEADBEEF --url https://lolepezy.github.io/rpki-prover
#   ./pkg/apt-repo/build-apt-repo.sh --no-sign          # for a local smoke test
#
# Needs apt-utils (apt-ftparchive) and, unless --no-sign is given, gnupg with
# the signing key already in the keyring.

set -euo pipefail

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)

PACKAGES_DIR="${REPO_ROOT}/pkg/packages"
OUTPUT_DIR="${REPO_ROOT}/pkg/apt-repo/public"
GPG_KEY=""
SIGN=1
BASE_URL="https://lolepezy.github.io/rpki-prover"
ORIGIN="rpki-prover"
LABEL="rpki-prover"

usage() {
    cat >&2 <<'USAGE'
Usage: build-apt-repo.sh [options]

Options:
  -p, --packages DIR  directory with <codename>/*.deb (default: pkg/packages)
  -o, --output DIR    repository root to generate (default: pkg/apt-repo/public)
  -k, --key ID        GPG key to sign the Release files with
      --no-sign       do not sign (the repository will need [trusted=yes])
  -u, --url URL       public base URL, used in the generated instructions
  -h, --help          this text
USAGE
}

while [ $# -gt 0 ]; do
    case "$1" in
        -p|--packages) PACKAGES_DIR=$(readlink -f "$2"); shift 2 ;;
        -o|--output)   OUTPUT_DIR=$2; shift 2 ;;
        -k|--key)      GPG_KEY=$2; shift 2 ;;
        --no-sign)     SIGN=0; shift ;;
        -u|--url)      BASE_URL=${2%/}; shift 2 ;;
        -h|--help)     usage; exit 0 ;;
        *)             echo "Unknown option: $1" >&2; usage; exit 1 ;;
    esac
done

command -v apt-ftparchive >/dev/null || {
    echo "apt-ftparchive not found; install the apt-utils package" >&2; exit 1; }
if [ "${SIGN}" -eq 1 ]; then
    command -v gpg >/dev/null || { echo "gpg not found; install gnupg or pass --no-sign" >&2; exit 1; }
fi
[ -d "${PACKAGES_DIR}" ] || { echo "No such directory: ${PACKAGES_DIR}" >&2; exit 1; }

rm -rf "${OUTPUT_DIR}"
mkdir -p "${OUTPUT_DIR}"
OUTPUT_DIR=$(cd "${OUTPUT_DIR}" && pwd)

KEYRING_NAME="rpki-prover-archive-keyring.asc"
SUITES=()

# ---------------------------------------------------------------------------
# pool + Packages indices, one suite per Debian release
# ---------------------------------------------------------------------------
for suite_dir in "${PACKAGES_DIR}"/*/; do
    [ -d "${suite_dir}" ] || continue
    codename=$(basename "${suite_dir}")

    mapfile -t debs < <(find "${suite_dir}" -maxdepth 1 -name '*.deb' | sort)
    [ ${#debs[@]} -gt 0 ] || { echo "No .deb files for ${codename}, skipping." >&2; continue; }

    echo "=== ${codename}: ${#debs[@]} package(s)"
    SUITES+=("${codename}")

    # A pool per suite so that the per-suite Packages index can be generated by
    # simply scanning one directory.
    pool="pool/${codename}/main/r/rpki-prover"
    mkdir -p "${OUTPUT_DIR}/${pool}"
    cp -v "${debs[@]}" "${OUTPUT_DIR}/${pool}/"

    architectures=$(for d in "${debs[@]}"; do dpkg-deb -f "$d" Architecture; done | sort -u)

    for arch in ${architectures}; do
        dist="dists/${codename}/main/binary-${arch}"
        mkdir -p "${OUTPUT_DIR}/${dist}"
        ( cd "${OUTPUT_DIR}" \
          && apt-ftparchive --arch "${arch}" packages "pool/${codename}" > "${dist}/Packages" \
          && gzip -9kf "${dist}/Packages" \
          && xz -9kf "${dist}/Packages" )
    done

    # Written outside dists/ first: apt-ftparchive hashes everything it finds in
    # the directory it is scanning, and a Release file that lists itself is at
    # best untidy and at worst confuses apt.
    release_tmp=$(mktemp)
    ( cd "${OUTPUT_DIR}" && apt-ftparchive \
        -o "APT::FTPArchive::Release::Origin=${ORIGIN}" \
        -o "APT::FTPArchive::Release::Label=${LABEL}" \
        -o "APT::FTPArchive::Release::Suite=${codename}" \
        -o "APT::FTPArchive::Release::Codename=${codename}" \
        -o "APT::FTPArchive::Release::Components=main" \
        -o "APT::FTPArchive::Release::Architectures=$(echo ${architectures} | tr '\n' ' ' | sed 's/ *$//')" \
        -o "APT::FTPArchive::Release::Description=rpki-prover packages for Debian ${codename}" \
        release "dists/${codename}" ) > "${release_tmp}"
    mv "${release_tmp}" "${OUTPUT_DIR}/dists/${codename}/Release"

    if [ "${SIGN}" -eq 1 ]; then
        gpg_args=(--batch --yes)
        [ -n "${GPG_KEY}" ] && gpg_args+=(--local-user "${GPG_KEY}")
        gpg "${gpg_args[@]}" --clearsign \
            --output "${OUTPUT_DIR}/dists/${codename}/InRelease" \
            "${OUTPUT_DIR}/dists/${codename}/Release"
        gpg "${gpg_args[@]}" --detach-sign --armor \
            --output "${OUTPUT_DIR}/dists/${codename}/Release.gpg" \
            "${OUTPUT_DIR}/dists/${codename}/Release"
        echo "    signed Release"
    fi
done

[ ${#SUITES[@]} -gt 0 ] || { echo "Nothing to publish." >&2; exit 1; }

# ---------------------------------------------------------------------------
# Public key
# ---------------------------------------------------------------------------
if [ "${SIGN}" -eq 1 ]; then
    if [ -n "${GPG_KEY}" ]; then
        gpg --armor --export "${GPG_KEY}" > "${OUTPUT_DIR}/${KEYRING_NAME}"
    else
        gpg --armor --export > "${OUTPUT_DIR}/${KEYRING_NAME}"
    fi
    [ -s "${OUTPUT_DIR}/${KEYRING_NAME}" ] || {
        echo "Exported public key is empty; check --key" >&2; exit 1; }
fi

# ---------------------------------------------------------------------------
# Instructions
# ---------------------------------------------------------------------------
suites_list=$(printf '%s ' "${SUITES[@]}")

if [ "${SIGN}" -eq 1 ]; then
    signed_by_line="Signed-By: /usr/share/keyrings/${KEYRING_NAME}"
    keyring_step="sudo curl -fsSL ${BASE_URL}/${KEYRING_NAME} -o /usr/share/keyrings/${KEYRING_NAME}"
else
    signed_by_line="Trusted: yes"
    keyring_step="# unsigned repository, nothing to install"
fi

cat > "${OUTPUT_DIR}/rpki-prover.sources.example" <<EOF
Types: deb
URIs: ${BASE_URL}
Suites: ${suites_list% }
Components: main
${signed_by_line}
EOF

cat > "${OUTPUT_DIR}/index.html" <<HTMLDOC
<!doctype html>
<meta charset="utf-8">
<title>rpki-prover APT repository</title>
<style>
  body { font: 16px/1.6 system-ui, sans-serif; max-width: 46rem; margin: 3rem auto; padding: 0 1rem; }
  pre { background: #f4f4f4; padding: 1rem; overflow-x: auto; border-radius: 6px; }
  code { font-family: ui-monospace, monospace; }
</style>
<h1>rpki-prover APT repository</h1>
<p>Debian packages of
<a href="https://github.com/lolepezy/rpki-prover">rpki-prover</a>
for: <strong>${suites_list% }</strong>.</p>

<h2>Setup</h2>
<pre><code>${keyring_step}

sudo tee /etc/apt/sources.list.d/rpki-prover.sources &gt;/dev/null &lt;&lt;'EOF'
Types: deb
URIs: ${BASE_URL}
Suites: \$(. /etc/os-release; echo \$VERSION_CODENAME)
Components: main
${signed_by_line}
EOF

sudo apt-get update
sudo apt-get install rpki-prover</code></pre>

<h2>After installation</h2>
<p>The service is started automatically. Options live in
<code>/etc/default/rpki-prover</code>, state in
<code>/var/lib/rpki-prover</code>, and the web UI is on
<a href="http://localhost:9999/">http://localhost:9999/</a>.</p>
HTMLDOC

echo
echo "Repository written to ${OUTPUT_DIR}"
echo "Suites: ${suites_list% }"
