{-# LANGUAGE OverloadedStrings #-}

module RPKI.Store.StorableSpec where

import           Codec.Compression.LZ4          (decompress)
import           Control.Concurrent.STM         (readTVarIO)
import           Control.Lens                   ((^.))
import qualified Data.ByteString                as BS
import qualified Data.ByteString.Short          as BSS
import           Data.Int                       (Int64)
import           Database.SQLite.Simple         (Only (..), query)
import           Test.Tasty
import qualified Test.Tasty.HUnit               as HU
import qualified Test.Tasty.QuickCheck          as QC

import           RPKI.AppTypes                  (WorldVersion (..))
import           RPKI.Domain                    (Hash (..), RpkiObjectType (..))
import           RPKI.Orphans                   ()
import           RPKI.Store.Base.Serialisation  (LexOrdKey64 (..))
import           RPKI.Store.Base.Storable
import           RPKI.Store.Database            (DB, Tx (..), roTx, rwTx)
import qualified RPKI.Store.Database            as DB
import qualified RPKI.Store.SQLite              as SQLite
import           RPKI.Store.Types               (ObjectMeta (..), ObjectOriginal (..), RpkiObjectLifecycle (..))
import           RPKI.TestCommons               (withTestContext)


storableEncodingSpec :: TestTree
storableEncodingSpec =
    testGroup "Storable encoding semantics"
        [ testGroup "Compressed wrapper"
            [ QC.testProperty "round-trips Int64 through LZ4-compressed bytes" $
                \x -> compressedRoundTrip (x :: Int64)
            , QC.testProperty "round-trips Hash through LZ4-compressed bytes" $
                \h -> compressedRoundTrip (h :: Hash)
            , HU.testCase "produces a different/smaller blob for highly repetitive bytes" $
                let payload    = BS.replicate 16384 0x61
                    raw        = serialiseField payload
                    compressed = serialiseField (Compressed payload)
                in do
                    HU.assertBool "Compressed bytes must decode back to the raw serialised bytes"
                        (decompress compressed == Just raw)
                    HU.assertBool "Compressed bytes must differ from raw serialised bytes"
                        (compressed /= raw)
                    HU.assertBool "Compressed bytes should be smaller for repetitive payloads"
                        (BS.length compressed < BS.length raw)
            ]
        , testGroup "StorableObject wrapper"
            [ HU.testCase "uses embedded storable field instead of re-serialising object" $
                let objectValue     = 111 :: Int64
                    embeddedBytes   = toStorable (222 :: Int64)
                    wrapped         = StorableObject objectValue embeddedBytes
                in do
                    HU.assertEqual "toStorable must return precomputed storable bytes"
                        embeddedBytes
                        (toStorable wrapped)
                    HU.assertEqual "serialiseField must use precomputed storable bytes"
                        (unStorable embeddedBytes)
                        (serialiseField wrapped)
            , HU.testCase "Database encode/decode keeps StorableObject precomputed bytes" $
                let wrapped = StorableObject (111 :: Int64) (toStorable (222 :: Int64))
                    encoded = DB.encodeSO wrapped
                    decoded = DB.decodeSO encoded :: StorableObject Int64
                in do
                    HU.assertBool "Encoded object blob must be valid LZ4 of embedded bytes"
                        (decompress encoded == Just (unStorable (storable wrapped)))
                    HU.assertEqual "Decoded object value must come from embedded storable bytes"
                        222
                        (object decoded)
                    HU.assertEqual "Decoded storable bytes must be the embedded bytes"
                        (storable wrapped)
                        (storable decoded)
            ]
        , testGroup "Database persistence path"
            [ HU.testCase "saveObject writes BLOB from toStorableObject-generated bytes" $
                withTestContext $ \appContext -> do
                    db <- readTVarIO $ appContext ^. #database

                    let worldVersion = WorldVersion (LexOrdKey64 1)
                        hash = Hash $ BSS.toShort $ BS.pack [1 .. 32]
                        original = ObjectOriginal $ BS.replicate 1024 0xAB
                        lifecycle = OriginalRO original mempty hash CER
                        expectedBlob = DB.encodeSO (toStorableObject lifecycle)

                    key <- rwTx db $ \tx -> DB.saveObject tx db lifecycle worldVersion

                    rows <- roTx db $ \(Tx conn) ->
                        query conn
                            "SELECT data FROM objects WHERE object_key = ?"
                            (Only (SQLite.toInt64 key)) :: IO [Only BS.ByteString]

                    case rows of
                        [Only actualBlob] ->
                            HU.assertEqual "Stored object data BLOB must match compressed StorableObject bytes"
                                expectedBlob
                                actualBlob
                        _ ->
                            HU.assertFailure "Expected exactly one row for saved object"
            ]
        ]
  where
    compressedRoundTrip :: (AsStorable a, Eq a) => a -> Bool
    compressedRoundTrip value =
        let raw        = serialiseField value
            compressed = serialiseField (Compressed value)
        in decompress compressed == Just raw
