{-# LANGUAGE ScopedTypeVariables #-}
-- | Criterion benchmark for 'prefixValidity'.
--
-- Builds the PrefixIndex once via Criterion's 'env', then measures:
--   - single IPv4 lookup (covering VRP exists)
--   - single IPv4 lookup (no covering VRP — Unknown result)
--   - single IPv6 lookup (covering VRP exists)
--   - batch of 1000 IPv4 + IPv6 probes
--
-- Run with:
--   stack bench rpki-prover:bench:criterion-bench
--   stack bench rpki-prover:bench:criterion-bench --benchmark-arguments '--output bench.html'

module Main where

import Control.DeepSeq      (force)
import Control.Exception    (evaluate)

import Data.List (foldl')

import Criterion.Main
import Text.Printf (printf)

import RPKI.Resources.Resources (mkIpv4Block, mkIpv6Block)
import RPKI.Resources.Types     (ASN (..), IpPrefix (..), PrefixLength (..))
import RPKI.Resources.Validity  (PrefixIndex, ValidityResult (..), TreeStats (..), createPrefixIndex, prefixValidity, lookupVrps, prefixIndexStats)
import BenchCommon              (genIPv4Vrps, genIPv6Vrps, mkIPv4Probes, mkIPv6Probes)

-- ---------------------------------------------------------------------------
-- Index construction
-- ---------------------------------------------------------------------------

-- Force the full result to a summary Int so Criterion measures real work
-- without needing NFData on ValidityResult.
{-# INLINE forceValidity #-}
forceValidity :: ValidityResult -> Int
forceValidity Unknown             = 0
forceValidity (InvalidOverall vs) = length vs
forceValidity (ValidOverall vs _) = length vs

-- | IPv4 probe that overlaps with the VRP set (i=0 seed).
ipv4HitAsn   :: ASN
ipv4HitAsn    = ASN 0
ipv4HitProbe :: IpPrefix
ipv4HitProbe  = Ipv4P (mkIpv4Block 12345 16)   -- offset from seed addr, shorter len covers it

-- | IPv4 probe outside the synthetic VRP space → Unknown result.
-- 192.0.2.0/24 (TEST-NET-1) is not generated by our seeds.
ipv4MissAsn   :: ASN
ipv4MissAsn    = ASN 99999
ipv4MissProbe :: IpPrefix
ipv4MissProbe  = Ipv4P (mkIpv4Block 0xC0000200 24)  -- 192.0.2.0/24

-- | IPv6 probe overlapping with our 2001:db8::/32 block.
ipv6HitAsn   :: ASN
ipv6HitAsn    = ASN 0
ipv6HitProbe :: IpPrefix
ipv6HitProbe  = Ipv6P (mkIpv6Block (0x20010db8, 0, 0x64, 0) 40)

-- | 500 IPv4 + 500 IPv6 probes for a batch benchmark.
batchProbes :: [(ASN, IpPrefix)]
batchProbes = take 500 (mkIPv4Probes [0..]) ++ take 500 (mkIPv6Probes [0..])

-- ---------------------------------------------------------------------------
-- Index construction
-- ---------------------------------------------------------------------------

buildIndex :: IO PrefixIndex
buildIndex = do
    idx <- evaluate $ force $ createPrefixIndex (genIPv4Vrps ++ genIPv6Vrps)
    let (v4s, v6s) = prefixIndexStats idx
    printf "\n=== Tree Stats ===\n"
    printf "IPv4: depth=%d  leaves=%d  maxLeaf=%d  avgLeaf=%.1f  dividedNodes=%d  maxOverlap=%d  totalOverlapEntries=%d\n"
        (tsDepth v4s) (tsLeafCount v4s) (tsLeafSizeMax v4s)
        (fromIntegral (tsLeafSizeTotal v4s) / max 1 (fromIntegral (tsLeafCount v4s)) :: Double)
        (tsDividedCount v4s) (tsOverlapMax v4s) (tsOverlapTotal v4s)
    printf "IPv6: depth=%d  leaves=%d  maxLeaf=%d  avgLeaf=%.1f  dividedNodes=%d  maxOverlap=%d  totalOverlapEntries=%d\n"
        (tsDepth v6s) (tsLeafCount v6s) (tsLeafSizeMax v6s)
        (fromIntegral (tsLeafSizeTotal v6s) / max 1 (fromIntegral (tsLeafCount v6s)) :: Double)
        (tsDividedCount v6s) (tsOverlapMax v6s) (tsOverlapTotal v6s)
    printf "==================\n\n"
    pure idx

-- ---------------------------------------------------------------------------
-- Main
-- ---------------------------------------------------------------------------

main :: IO ()
main = defaultMain
    [ env buildIndex $ \idx ->
        bgroup "prefixValidity"
            [ bench "IPv4 hit"  $ nf (\i -> forceValidity $ prefixValidity ipv4HitAsn  ipv4HitProbe  i) idx
            , bench "IPv4 miss" $ nf (\i -> forceValidity $ prefixValidity ipv4MissAsn ipv4MissProbe i) idx
            , bench "IPv6 hit"  $ nf (\i -> forceValidity $ prefixValidity ipv6HitAsn  ipv6HitProbe  i) idx
            , bench "batch 1000 (500 IPv4 + 500 IPv6)" $
                nf (\i -> foldl' (\acc (asn, pfx) -> acc + forceValidity (prefixValidity asn pfx i)) 0 batchProbes) idx
            ]
    , env buildIndex $ \idx ->
        bgroup "lookupVrps (tree traversal only)"
            [ bench "IPv4 hit"  $ nf (\i -> length $ lookupVrps ipv4HitProbe  i) idx
            , bench "IPv4 miss" $ nf (\i -> length $ lookupVrps ipv4MissProbe i) idx
            , bench "IPv6 hit"  $ nf (\i -> length $ lookupVrps ipv6HitProbe  i) idx
            ]
    ]
