name: Docker build

on:
  push:
    branches:
      - 'master'
      - 'github-actions'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: lolepezy
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: lolepezy/rpki-prover:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}