name: Static binary build

on:
  push:
    tags: v[0-9]+.[0-9]+.[0-9]+    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.10.4'
        enable-stack: true
        stack-version: 'latest'        
    - 
      name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-stack
      with:
        path: ~/.stack
        key:
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/stack.yaml') }}-${{ hashFiles('**/*.cabal') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/stack.yaml') }}
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-    
    - 
      name: Build GHC+musl image
      uses: docker/build-push-action@v2
      with:
        file: Dockerfile.static-builder 
        push: false
        tags: rpki-prover-builder    
    - 
      name: Build static binary
      run:
        stack install --docker --docker-image "rpki-prover-builder" --no-nix rpki-prover:rpki-prover-static && mv .stack-work/docker/_home/.local/bin/rpki-prover-static ./rpki-prover-linux.exe
    - 
      name: Upload binary      
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "rpki-prover-linux.exe"
        tags: false
        prerelease: true
        draft: true        
        update_latest_release: false        
